### ISSUE TITLE
Can't clone the repo

### ISSUE THREAD

**Issue by ghost** [BenMAPCE/BenMAP-CE#136]
Hello BenMAP team,

I'm a staff from CARB. I occasionally look at the BenMAP-CE source code to better understand what it does internally. For quite some time, I could not clone or update my local repo due to an out-of-data LFS quota error. I see active development in the repo and wonder how you are resolving this issue or live with it. Any help? Thanks!

```
Error downloading object: BenMAP/Data/Country Shapefiles/ABW/ABW_grid.shp (6c567d3): Smudge error: Error downloading BenMAP/Data/Country Shapefiles/ABW/ABW_grid.shp (6c567d37a4c8d9fdecce785aa3c835cc4299a63988c74ad9808c9f17d45aa393): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by nfann** [comment]
Thanks for your question! It turns out we ran out of bandwidth. Starting in September we'll be purchasing more bandwidth, which should enable you to download the repo with no problem. Try again on Sep 1 and let us know if this solves the problem.

**Comment by ghost** [comment]
@nfann Thanks!

**Comment by ghost** [comment]
This issue is resolved. Thanks!
