### ISSUE TITLE
Unable to load database on initial program start

### ISSUE THREAD

**Issue by ctdunc** [BenMAPCE/BenMAP-CE#94]
I am attempting to run BenMAP under Lutris on Linux, and have encountered the following error:

`Unable to load database at pooling=True;min pool size=5;max pool size=20;connection timeout=15;connection lifetime=15; initial catalog=:c\users\connor\Local Settings\Application Data\BenMAP-CE\\Database\BenMAP50.fdb;user id=SYSDBA;password=masterkey; character set=NONE;server type=1`

The double-backslash between BenMAP-CE\\Database is accurate, which leads me to believe there may be a typo somewhere?

Other useful info:
OS: Arch linux.
Run with WINEARCH=win32 the correct wineprefix. 
.NET 4.5.2 is installed in the wine prefix, as are other dependencies like gallium9.

**Comment by jtf621** [comment]
I am seeing a similar problem on Windows10.  When I click Tools>Online Database Import I get an error and the program shuts down.  I cannot use the crash reporter because it never enables the submit button.  Let me know how I can help document the issue.  Or if there is a workaround.

**Comment by LisaMThompson** [comment]
I understand that Tools>Online Database Import has never worked. Please use Database Import instead to import a .bdbx database.

**Comment by jtf621** [comment]
@LisaMThompson, thank you.  Where do I get the bdbx database?  All the directories are empty.

**Comment by LisaMThompson** [comment]
If you're trying to import a database into BenMAP, Tools > Database Import should work even though Tools > Online Database Import hasn't worked. I can help troubleshoot using the desktop app if you have any questions, but probably can't be more useful here. Sorry! -- Thompson.Lisa@epa.gov
